# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ecs-launch-template
  description: Terraform module for generating an AWS Launch Template for ECS that handles draining on Spot Termination Requests
  homepage: https://cloudposse.com/accelerate
  topics: ""
